from dashboard.pgcompat import translate_sql


def test_eye_review_schema_and_migrations_translate_for_postgres():
    create_sql = """
        CREATE TABLE IF NOT EXISTS eye_vision_review_requests (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            email TEXT NOT NULL,
            scan_date TEXT NOT NULL,
            UNIQUE(email, scan_date)
        )"""
    translated = translate_sql(create_sql)
    assert "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in translated

    migration_sql = (
        "ALTER TABLE eye_vision_review_requests "
        "ADD COLUMN revision_log_json TEXT NOT NULL DEFAULT '[]'")
    translated = translate_sql(migration_sql)
    assert translated.startswith(
        "ALTER TABLE IF EXISTS eye_vision_review_requests "
        "ADD COLUMN IF NOT EXISTS revision_log_json")


def test_eye_review_upsert_and_audit_update_translate_for_postgres():
    upsert_sql = """
        INSERT INTO eye_vision_review_requests (
            email, scan_date, status, report_json, requested_at, updated_at
        ) VALUES (?,?,?,?,?,?)
        ON CONFLICT(email, scan_date) DO UPDATE SET
            status=excluded.status,
            report_json=excluded.report_json,
            updated_at=excluded.updated_at
        """
    translated = translate_sql(upsert_sql)
    assert translated.count("%s") == 6
    assert "ON CONFLICT(email, scan_date) DO UPDATE" in translated

    audit_sql = """
        UPDATE eye_vision_review_requests
        SET status=?, report_json=?, reviewer_notes=?, updated_at=?, reviewed_at=?,
            reviewer_id=?, revision_log_json=?
        WHERE id=?
        """
    translated = translate_sql(audit_sql)
    assert translated.count("%s") == 8
