"""Intelligence briefings — markdown reports generated by briefing_runner.py, served to the dashboard.

3 domain briefings (each owns its stats once; insight + color-coded actions):
- money-cash        — cash position, revenue in, AR/overdue, the revenue constraint
- clients-pipeline  — client-message backlog, GHL pipeline, ScoreApp intake
- signals-patterns  — cross-system anomalies + the meta-pattern + content/video/ads

Each briefing is stored under DATA_DIR/intelligence/{slug}.md. The dashboard
renders the markdown in the Intelligence row (Shaira-Daily is a separate feed).
"""

import os
import json
from pathlib import Path
from datetime import datetime, timezone

DATA_DIR = Path(os.environ.get("DATA_DIR", "/tmp")) / "intelligence"
DATA_DIR.mkdir(parents=True, exist_ok=True)

VALID_SLUGS = {
    "money-cash",
    "clients-pipeline",
    "signals-patterns",
}


def _slug_path(slug):
    if slug not in VALID_SLUGS:
        raise ValueError(f"Unknown slug: {slug}. Valid: {sorted(VALID_SLUGS)}")
    return DATA_DIR / f"{slug}.md"


def read_briefing(slug):
    """Return the latest briefing markdown for slug, plus metadata."""
    p = _slug_path(slug)
    if not p.exists():
        return {
            "slug": slug,
            "empty": True,
            "message": f"No {slug} briefing yet. First run pending.",
        }
    stat = p.stat()
    return {
        "slug": slug,
        "empty": False,
        "markdown": p.read_text(),
        "generated_at": datetime.fromtimestamp(stat.st_mtime, tz=timezone.utc).isoformat(),
        "bytes": stat.st_size,
    }


def write_briefing(slug, markdown_bytes):
    """Persist a briefing markdown payload uploaded by the Mac runner."""
    p = _slug_path(slug)
    text = markdown_bytes.decode("utf-8") if isinstance(markdown_bytes, bytes) else markdown_bytes
    p.write_text(text)
    return {"slug": slug, "saved": True, "path": str(p), "bytes": len(text)}


def list_all():
    """Index of all briefings with their freshness."""
    out = {}
    for slug in sorted(VALID_SLUGS):
        out[slug] = read_briefing(slug)
    return out
