"""Intelligence briefings — markdown reports generated by briefing_runner.py, served to the dashboard.

3 domain briefings (each owns its stats once; insight + color-coded actions):
- money-cash        — cash position, revenue in, AR/overdue, the revenue constraint
- clients-pipeline  — client-message backlog, GHL pipeline, ScoreApp intake
- signals-patterns  — cross-system anomalies + the meta-pattern + content/video/ads

Each briefing is stored as a row in the intelligence_briefings DB table (via
dashboard.db). The dashboard renders the markdown in the Intelligence row
(Shaira-Daily is a separate feed).
"""

import os
import re
import json
from datetime import datetime, timezone

from dashboard import db

_TABLE = "intelligence_briefings"

VALID_SLUGS = {
    "money-cash",
    "clients-pipeline",
    "signals-patterns",
}


def _default_db_path():
    # Mirror app.LOG_DB / gmail_token.default_db_path: DATA_DIR persistent disk
    # on Render (/data), repo root in local dev.
    from pathlib import Path
    root = os.environ.get("DATA_DIR") or str(Path(__file__).resolve().parent.parent)
    return str(Path(root) / "chat_log.db")


def _ensure_table(cx):
    cx.execute(
        f"CREATE TABLE IF NOT EXISTS {_TABLE} ("
        "slug TEXT PRIMARY KEY, markdown TEXT, links_json TEXT, updated_at TEXT NOT NULL)"
    )


def _check_slug(slug):
    if slug not in VALID_SLUGS:
        raise ValueError(f"Unknown slug: {slug}. Valid: {sorted(VALID_SLUGS)}")


def write_links(slug, links, db_path=None):
    """Persist the link registry (ref -> {type, display, url}) for a briefing."""
    _check_slug(slug)
    ts = datetime.now(timezone.utc).isoformat()
    payload = json.dumps(links or {})
    with db.connect(db_path or _default_db_path(), timeout=10) as cx:
        _ensure_table(cx)
        cx.execute(
            f"INSERT INTO {_TABLE} (slug, links_json, updated_at) VALUES (?,?,?) "
            "ON CONFLICT(slug) DO UPDATE SET links_json=excluded.links_json, updated_at=excluded.updated_at",
            (slug, payload, ts),
        )
        cx.commit()
    return {"slug": slug, "links": len(links or {})}


def read_links(slug, db_path=None):
    """Return the link registry for a briefing, or {} if absent/unreadable."""
    _check_slug(slug)
    try:
        with db.connect(db_path or _default_db_path(), timeout=10) as cx:
            row = cx.execute(
                f"SELECT links_json FROM {_TABLE} WHERE slug=?", (slug,)
            ).fetchone()
    except db.OperationalError as e:
        if "no such table" in str(e).lower() or "does not exist" in str(e).lower():
            return {}
        raise
    if not row or not row[0]:
        return {}
    try:
        return json.loads(row[0])
    except Exception:
        return {}


# Canonical card title per slug (also covers the separate shaira-daily feed).
# Forced at serve time so the title is deterministic regardless of LLM wording.
CANONICAL_TITLE = {
    "money-cash": "Finance",
    "clients-pipeline": "Clients",
    "signals-patterns": "Signals",
    "shaira-daily": "Shaira",
}


def normalize_title(slug, md):
    """Force the card's first heading to '# <canonical name>' (a clean H1).

    Fixes LLM title drift (subtitles, leaked product names, em dashes) and the
    Shaira card's H2/em-dash heading, so all 4 cards share one title style."""
    name = CANONICAL_TITLE.get(slug)
    if not name or not md:
        return md
    lines = md.split("\n")
    for i, ln in enumerate(lines):
        if ln.lstrip().startswith("#"):
            lines[i] = f"# {name}"
            return "\n".join(lines)
    return f"# {name}\n" + md


_HEAD_RE = re.compile(r"^\s*#{1,6}\s+")
_ACT_RE = re.compile(r"^\s*(?:[-*]\s*)?\[(?:HIGH|MED|LOW)\]", re.I)


def actions_first(md):
    """Move the section that holds the action items (the [HIGH]/[MED]/[LOW] lines)
    up to the top of the card, right under the title + dateline. Works for the
    'Recommended actions' section and the Shaira card's 'Needs Glen' section."""
    if not md:
        return md
    lines = md.split("\n")
    # Find the first heading whose section contains an action-tagged line.
    start = None
    for i, ln in enumerate(lines):
        if not _HEAD_RE.match(ln):
            continue
        j = i + 1
        while j < len(lines) and not _HEAD_RE.match(lines[j]):
            if _ACT_RE.match(lines[j]):
                start = i
                break
            j += 1
        if start is not None:
            break
    if start is None:
        return md
    end = len(lines)
    for j in range(start + 1, len(lines)):
        if _HEAD_RE.match(lines[j]):
            end = j
            break
    section = lines[start:end]
    while section and not section[-1].strip():
        section.pop()
    rest = lines[:start] + lines[end:]
    # Insert right after the title heading (+ an immediately-following italic dateline).
    insert_at = 0
    for k, ln in enumerate(rest):
        if _HEAD_RE.match(ln):
            insert_at = k + 1
            if insert_at < len(rest) and rest[insert_at].strip().startswith("*"):
                insert_at += 1
            break
    return "\n".join(rest[:insert_at] + [""] + section + [""] + rest[insert_at:])


def read_briefing(slug, db_path=None):
    """Return the latest briefing markdown for slug, plus metadata."""
    _check_slug(slug)
    try:
        with db.connect(db_path or _default_db_path(), timeout=10) as cx:
            row = cx.execute(
                f"SELECT markdown, links_json, updated_at FROM {_TABLE} WHERE slug=?", (slug,)
            ).fetchone()
    except db.OperationalError as e:
        if "no such table" in str(e).lower() or "does not exist" in str(e).lower():
            row = None
        else:
            raise
    if not row or row[0] is None:
        return {"slug": slug, "empty": True,
                "message": f"No {slug} briefing yet. First run pending."}
    md = row[0]
    try:
        links = json.loads(row[1]) if row[1] else {}
    except Exception:
        links = {}
    return {"slug": slug, "empty": False, "markdown": md, "links": links,
            "generated_at": row[2], "bytes": len(md)}


def write_briefing(slug, markdown_bytes, db_path=None):
    """Persist a briefing markdown payload (upserts the row's markdown; leaves links intact)."""
    _check_slug(slug)
    text = markdown_bytes.decode("utf-8") if isinstance(markdown_bytes, bytes) else markdown_bytes
    ts = datetime.now(timezone.utc).isoformat()
    with db.connect(db_path or _default_db_path(), timeout=10) as cx:
        _ensure_table(cx)
        cx.execute(
            f"INSERT INTO {_TABLE} (slug, markdown, updated_at) VALUES (?,?,?) "
            "ON CONFLICT(slug) DO UPDATE SET markdown=excluded.markdown, updated_at=excluded.updated_at",
            (slug, text, ts),
        )
        cx.commit()
    return {"slug": slug, "saved": True, "bytes": len(text)}


def list_all(db_path=None):
    """Index of all briefings with their freshness."""
    return {slug: read_briefing(slug, db_path=db_path) for slug in sorted(VALID_SLUGS)}
